FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@10.6.2 --activate
RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps/nextjs/package.json ./apps/nextjs/package.json

RUN pnpm install --frozen-lockfile

COPY apps/nextjs/prisma ./apps/nextjs/prisma

RUN pnpm db:generate

EXPOSE 3000

CMD ["pnpm", "dev"]
